// solutions/react/04-todo-list/TodoList.jsx
import { useState } from "react";

export default function TodoList({ initialTodos = [] }) {
  const [todos, setTodos] = useState(initialTodos);

  function toggle(id) {
    setTodos(todos.map((todo) => (todo.id === id ? { ...todo, done: !todo.done } : todo)));
  }

  function remove(id) {
    setTodos(todos.filter((todo) => todo.id !== id));
  }

  if (todos.length === 0) {
    return <p>Nothing to do.</p>;
  }

  const left = todos.filter((todo) => !todo.done).length;

  return (
    <div>
      <ul>
        {todos.map((todo) => (
          <li key={todo.id}>
            <label>
              <input type="checkbox" checked={todo.done} onChange={() => toggle(todo.id)} />
              {todo.title}
            </label>
            <button aria-label={`Remove ${todo.title}`} onClick={() => remove(todo.id)}>
              Remove
            </button>
          </li>
        ))}
      </ul>
      <p>{left} left</p>
    </div>
  );
}

// solutions/vue/04-todo-list/TodoList.vue
<script setup>
import { ref, computed } from "vue";

const props = defineProps({
  todos: { type: Array, required: true },
});

const emit = defineEmits(["remove"]);
const showDone = ref(true);

const visible = computed(() => (showDone.value ? props.todos : props.todos.filter((todo) => !todo.done)));
const doneCount = computed(() => props.todos.filter((todo) => todo.done).length);
</script>

<template>
  <div class="card">
    <p v-if="todos.length === 0" class="empty">Nothing to do.</p>
    <template v-else>
      <ul>
        <li v-for="todo in visible" :key="todo.id" :class="{ done: todo.done }">
          {{ todo.title }}
          <button @click="emit('remove', todo.id)">Delete</button>
        </li>
      </ul>
      <p class="summary">{{ doneCount }} of {{ todos.length }} done</p>
      <button class="toggle" @click="showDone = !showDone">{{ showDone ? "Hide done" : "Show done" }}</button>
    </template>
  </div>
</template>
