// solutions/vue/06-user-list/UserList.vue
<script setup>
import { ref, onMounted } from "vue";
import { useToggle } from "./useToggle.js";

const props = defineProps({
  load: { type: Function, required: true },
});

const users = ref([]);
const loading = ref(true);
const error = ref("");
const { on: visible, toggle } = useToggle(true);

async function refresh() {
  loading.value = true;
  error.value = "";
  try {
    users.value = await props.load();
  } catch (problem) {
    error.value = problem.message;
  } finally {
    loading.value = false;
  }
}

onMounted(refresh);
</script>

<template>
  <div class="card">
    <p v-if="loading" class="loading">Loading ...</p>
    <p v-else-if="error" role="alert">Could not load: {{ error }}</p>
    <ul v-else-if="visible">
      <li v-for="user in users" :key="user.id">{{ user.name }}</li>
    </ul>
    <button @click="refresh">Reload</button>
    <button @click="toggle">{{ visible ? "Hide list" : "Show list" }}</button>
  </div>
</template>

// solutions/react/07-user-list/UserList.jsx
import { useEffect, useState } from "react";

export default function UserList({ url }) {
  const [users, setUsers] = useState([]);
  const [loading, setLoading] = useState(true);
  const [failed, setFailed] = useState(false);

  useEffect(() => {
    let cancelled = false;
    setLoading(true);
    setFailed(false);

    async function load() {
      try {
        const response = await fetch(url);
        if (!response.ok) {
          throw new Error(`request failed: ${response.status}`);
        }
        const data = await response.json();
        if (!cancelled) {
          setUsers(data);
        }
      } catch {
        if (!cancelled) {
          setFailed(true);
        }
      } finally {
        if (!cancelled) {
          setLoading(false);
        }
      }
    }

    load();
    return () => {
      cancelled = true;
    };
  }, [url]);

  if (loading) {
    return <p>Loading...</p>;
  }
  if (failed) {
    return <p role="alert">Could not load users.</p>;
  }
  if (users.length === 0) {
    return <p>No users yet.</p>;
  }
  return (
    <ul>
      {users.map((user) => (
        <li key={user.id}>{user.name}</li>
      ))}
    </ul>
  );
}
